import type { Scenario, Session, TranscriptTurn } from "./types"

export const scenarios: Scenario[] = [
  {
    id: "scenario-1",
    scenarioType: "cardiac-arrest",
    title: "Cardiac Arrest",
    description:
      "A 58-year-old male collapsed at a grocery store. Bystander is panicked and calling from the scene. Patient is unresponsive, not breathing normally.",
    callerDescription: "Panicked 34-year-old woman, Maria Johnson, bystander at the scene.",
    callerProfile: { name: "Maria Johnson", age: 34, emotion: "panicked" },
    criticalInfo: [
      "Patient location (Grocery store on 5th Ave)",
      "Patient condition (unresponsive, not breathing)",
      "Patient age and gender",
      "Number of bystanders",
      "AED availability",
    ],
    expectedActions: [
      "Confirm location and callback number",
      "Ask if patient is breathing",
      "Instruct CPR",
      "Ask about AED availability",
      "Dispatch EMS",
      "Keep caller on the line",
    ],
    optionalComplications: [
      "Caller starts crying and becomes incoherent",
      "Patient starts vomiting",
    ],
    difficulty: "medium",
    language: "en",
  },
  {
    id: "scenario-2",
    scenarioType: "fire",
    title: "Structure Fire",
    description:
      "Apartment building fire on the 3rd floor. Caller is a resident on the 2nd floor, smells smoke and sees flames from the window across the courtyard.",
    callerDescription: "Urgent 45-year-old man, David Chen, resident on the 2nd floor.",
    callerProfile: { name: "David Chen", age: 45, emotion: "urgent" },
    criticalInfo: [
      "Building address",
      "Floor and apartment of fire origin",
      "Number of occupants",
      "Anyone trapped",
      "Type of building (apartment)",
    ],
    expectedActions: [
      "Get exact address",
      "Instruct caller to evacuate immediately",
      "Ask about trapped occupants",
      "Dispatch fire department",
      "Advise to stay low if smoke present",
      "Tell caller not to use elevators",
    ],
    optionalComplications: [
      "Caller says their elderly neighbor might be trapped",
      "Power goes out during the call",
    ],
    difficulty: "hard",
    language: "en",
  },
  {
    id: "scenario-3",
    scenarioType: "traffic-accident",
    title: "Traffic Accident",
    description:
      "Two-car collision at an intersection. One driver appears injured with a bleeding head wound. Other driver is walking around dazed.",
    callerDescription: "Shaken 28-year-old woman, Sarah Williams, witness at the scene.",
    callerProfile: { name: "Sarah Williams", age: 28, emotion: "shaken" },
    criticalInfo: [
      "Intersection location",
      "Number of vehicles involved",
      "Number of injured persons",
      "Nature of injuries",
      "Traffic hazards (fuel leak, blocked road)",
    ],
    expectedActions: [
      "Confirm exact intersection",
      "Ask number of injured",
      "Assess consciousness of injured",
      "Instruct not to move injured",
      "Dispatch EMS and police",
      "Ask about fuel leaks or hazards",
    ],
    optionalComplications: [
      "One of the cars starts smoking",
      "A child is found in the backseat",
    ],
    difficulty: "easy",
    language: "en",
  },
]

function generateTranscript(scenarioId: string): TranscriptTurn[] {
  const transcripts: Record<string, TranscriptTurn[]> = {
    "scenario-1": [
      { id: "t1", timestamp: 0, speaker: "operator", text: "911, what is your emergency?" },
      { id: "t2", timestamp: 3, speaker: "caller", text: "Oh my god, please help! A man just collapsed in the grocery store! He's not moving!" },
      { id: "t3", timestamp: 8, speaker: "operator", text: "Ma'am, I need you to stay calm. Can you tell me the address of the grocery store?" },
      { id: "t4", timestamp: 13, speaker: "caller", text: "It's the FreshMart on 5th Avenue, near Oak Street. Please hurry!" },
      { id: "t5", timestamp: 18, speaker: "operator", text: "Help is on the way. Is the man breathing?" },
      { id: "t6", timestamp: 22, speaker: "caller", text: "I... I don't think so. His chest isn't moving. Oh god..." },
      { id: "t7", timestamp: 27, speaker: "operator", text: "I need you to check. Put your ear close to his mouth. Can you feel any air?" },
      { id: "t8", timestamp: 33, speaker: "caller", text: "No, nothing. He's completely still." },
      { id: "t9", timestamp: 37, speaker: "operator", text: "Okay, we need to start CPR immediately. Do you know how?" },
      { id: "t10", timestamp: 41, speaker: "caller", text: "I took a class years ago... I'll try." },
      { id: "t11", timestamp: 45, speaker: "operator", text: "Place the heel of your hand on the center of his chest. Push hard and fast, about 2 inches deep." },
      { id: "t12", timestamp: 52, speaker: "caller", text: "Okay, I'm doing it. Someone else here is helping too." },
      { id: "t13", timestamp: 57, speaker: "operator", text: "Good. Is there an AED or defibrillator nearby? Check the walls." },
      { id: "t14", timestamp: 63, speaker: "caller", text: "Someone went to look... Yes! They found one by the entrance!" },
      { id: "t15", timestamp: 68, speaker: "operator", text: "Great. Have them bring it over and turn it on. Follow the voice instructions. EMS is 3 minutes away." },
    ],
    "scenario-2": [
      { id: "t1", timestamp: 0, speaker: "operator", text: "911, what is your emergency?" },
      { id: "t2", timestamp: 2, speaker: "caller", text: "There's a fire in my apartment building! I can see flames from the 3rd floor!" },
      { id: "t3", timestamp: 7, speaker: "operator", text: "What is the address of the building?" },
      { id: "t4", timestamp: 10, speaker: "caller", text: "742 Elm Street, Apartment 2B. The fire is across the courtyard on the 3rd floor." },
      { id: "t5", timestamp: 15, speaker: "operator", text: "Are you in a safe location right now?" },
      { id: "t6", timestamp: 18, speaker: "caller", text: "I'm still in my apartment on the 2nd floor. I can smell smoke." },
      { id: "t7", timestamp: 22, speaker: "operator", text: "Sir, you need to evacuate immediately. Do NOT use the elevator. Use the stairs." },
      { id: "t8", timestamp: 27, speaker: "caller", text: "Okay, I'm heading to the stairs now." },
      { id: "t9", timestamp: 31, speaker: "operator", text: "Do you know if anyone is trapped in the building, especially on the 3rd floor?" },
      { id: "t10", timestamp: 36, speaker: "caller", text: "Mrs. Patterson lives on the 3rd floor. She's elderly and uses a walker. I haven't seen her come out." },
      { id: "t11", timestamp: 42, speaker: "operator", text: "Fire department is dispatched. Do NOT go back to check on her. How many people do you think are in the building?" },
      { id: "t12", timestamp: 48, speaker: "caller", text: "Maybe 15-20 people total. It's a small building, 12 units." },
    ],
    "scenario-3": [
      { id: "t1", timestamp: 0, speaker: "operator", text: "911, what is your emergency?" },
      { id: "t2", timestamp: 2, speaker: "caller", text: "I just saw a car crash at the intersection of Main and 3rd. Two cars." },
      { id: "t3", timestamp: 7, speaker: "operator", text: "Is anyone injured?" },
      { id: "t4", timestamp: 9, speaker: "caller", text: "Yes, one driver has a cut on his head. It's bleeding a lot. The other one is walking around but seems confused." },
      { id: "t5", timestamp: 15, speaker: "operator", text: "Is the injured driver conscious and breathing?" },
      { id: "t6", timestamp: 18, speaker: "caller", text: "Yes, he's conscious but he looks really dazed. He's still in his car." },
      { id: "t7", timestamp: 22, speaker: "operator", text: "Do not move him. Can you tell if there are any fuel leaks or smoke from either vehicle?" },
      { id: "t8", timestamp: 27, speaker: "caller", text: "I don't see any smoke. Let me check... no, no fuel on the ground either." },
      { id: "t9", timestamp: 33, speaker: "operator", text: "Good. EMS and police are being dispatched. Are there any other passengers in either vehicle?" },
      { id: "t10", timestamp: 38, speaker: "caller", text: "Let me look... oh wait, there might be someone in the backseat of the first car." },
      { id: "t11", timestamp: 43, speaker: "operator", text: "Can you see if that person is responsive? Don't open the door, just look through the window." },
      { id: "t12", timestamp: 48, speaker: "caller", text: "It's a child, maybe 6 or 7. They're crying but seem okay. Still in their car seat." },
    ],
  }
  return transcripts[scenarioId] || transcripts["scenario-1"]
}

export const pastSessions: Session[] = [
  {
    id: "session-1",
    scenarioId: "scenario-1",
    scenarioType: "cardiac-arrest",
    scenarioTitle: "Cardiac Arrest",
    difficulty: "medium",
    language: "en",
    startedAt: "2026-02-10T09:15:00Z",
    endedAt: "2026-02-10T09:22:30Z",
    durationSec: 450,
    transcript: generateTranscript("scenario-1"),
    notes: "Location: FreshMart, 5th Ave\nPatient: 58yo male, unresponsive\nBystander performing CPR\nAED located",
    operatorSummary: "Responded to cardiac arrest at grocery store. Guided caller through CPR and AED use. EMS dispatched within 1 minute.",
    evaluation: {
      protocolAdherence: 92,
      timeliness: 88,
      criticalInfoCapture: 85,
      overallScore: 88,
      missedActions: ["Did not confirm callback number"],
      feedbackBullets: [
        "Excellent CPR instruction delivery",
        "Good job keeping caller calm",
        "Remember to always confirm callback number early",
      ],
    },
  },
  {
    id: "session-2",
    scenarioId: "scenario-2",
    scenarioType: "fire",
    scenarioTitle: "Structure Fire",
    difficulty: "hard",
    language: "en",
    startedAt: "2026-02-11T14:30:00Z",
    endedAt: "2026-02-11T14:38:15Z",
    durationSec: 495,
    transcript: generateTranscript("scenario-2"),
    notes: "742 Elm St, 3rd floor fire\nElderly resident possibly trapped\n12-unit building, ~15-20 occupants",
    operatorSummary: "Structure fire at apartment building. Instructed caller to evacuate. Identified potentially trapped elderly resident. Fire department dispatched.",
    evaluation: {
      protocolAdherence: 78,
      timeliness: 82,
      criticalInfoCapture: 75,
      overallScore: 78,
      missedActions: [
        "Did not ask about smoke inhalation symptoms",
        "Did not advise to stay low while evacuating",
      ],
      feedbackBullets: [
        "Quick dispatch of fire department",
        "Good follow-up on trapped resident",
        "Should advise caller to stay low if smoke is present",
        "Ask about symptoms of smoke inhalation",
      ],
    },
  },
  {
    id: "session-3",
    scenarioId: "scenario-3",
    scenarioType: "traffic-accident",
    scenarioTitle: "Traffic Accident",
    difficulty: "easy",
    language: "en",
    startedAt: "2026-02-12T11:00:00Z",
    endedAt: "2026-02-12T11:06:45Z",
    durationSec: 405,
    transcript: generateTranscript("scenario-3"),
    notes: "Main & 3rd intersection\n2 vehicles, head wound on driver 1\nChild in backseat, appears okay",
    operatorSummary: "Two-car collision. One driver with head laceration, one child passenger. All conscious. EMS and police dispatched.",
    evaluation: {
      protocolAdherence: 95,
      timeliness: 92,
      criticalInfoCapture: 90,
      overallScore: 92,
      missedActions: ["Did not ask about seatbelt use"],
      feedbackBullets: [
        "Excellent scene assessment",
        "Great identification of child passenger",
        "Consider asking about seatbelt use for injury assessment",
      ],
    },
  },
  {
    id: "session-4",
    scenarioId: "scenario-1",
    scenarioType: "cardiac-arrest",
    scenarioTitle: "Cardiac Arrest",
    difficulty: "medium",
    language: "en",
    startedAt: "2026-02-13T16:45:00Z",
    endedAt: "2026-02-13T16:53:20Z",
    durationSec: 500,
    transcript: generateTranscript("scenario-1"),
    notes: "Repeat scenario for practice\nImproved CPR timing instructions",
    operatorSummary: "Second attempt at cardiac arrest scenario. Improved on callback number confirmation and CPR instruction timing.",
    evaluation: {
      protocolAdherence: 96,
      timeliness: 94,
      criticalInfoCapture: 92,
      overallScore: 94,
      missedActions: [],
      feedbackBullets: [
        "Significant improvement from previous attempt",
        "All critical info captured",
        "Excellent composure throughout",
      ],
    },
  },
  {
    id: "session-5",
    scenarioId: "scenario-2",
    scenarioType: "fire",
    scenarioTitle: "Structure Fire",
    difficulty: "hard",
    language: "es",
    startedAt: "2026-02-14T08:00:00Z",
    endedAt: "2026-02-14T08:09:30Z",
    durationSec: 570,
    transcript: generateTranscript("scenario-2"),
    notes: "Spanish language attempt\nSome vocabulary gaps but managed well",
    operatorSummary: "Handled structure fire scenario in Spanish. Successfully guided evacuation despite language challenges.",
    evaluation: {
      protocolAdherence: 72,
      timeliness: 70,
      criticalInfoCapture: 68,
      overallScore: 70,
      missedActions: [
        "Did not ask about smoke inhalation symptoms",
        "Slow to instruct evacuation",
        "Did not confirm number of floors",
      ],
      feedbackBullets: [
        "Good effort with Spanish language",
        "Evacuation instruction was delayed - prioritize this",
        "Practice fire-specific vocabulary in Spanish",
        "Always confirm building details early",
      ],
    },
  },
]

// Caller script lines for live simulation streaming
export const callerScripts: Record<string, string[]> = {
  "cardiac-arrest": [
    "Oh my god, please help! A man just collapsed!",
    "We're at the FreshMart grocery store on 5th Avenue, near Oak Street.",
    "I... I don't think so. His chest isn't moving at all.",
    "No, nothing. He's completely still. Please hurry!",
    "I took a CPR class a long time ago... I can try.",
    "Okay, I'm pushing on his chest. Like this?",
    "Someone found an AED by the front entrance!",
    "I turned it on. It's giving instructions now.",
    "It says to apply the pads... okay, doing that.",
    "It says don't touch the patient... it's analyzing...",
    "It delivered a shock! What do I do now?",
    "Okay, I'm starting compressions again.",
    "I can hear sirens! They're getting closer!",
    "The paramedics are here! Thank you so much!",
  ],
  fire: [
    "There's a fire! I can see flames from the building across the courtyard!",
    "I'm at 742 Elm Street, Apartment 2B. The fire is on the 3rd floor.",
    "I'm still inside my apartment on the 2nd floor. I can smell smoke now.",
    "Okay, I'm heading to the stairs.",
    "Wait - Mrs. Patterson lives on the 3rd floor. She's elderly with a walker. I haven't seen her!",
    "It's getting smokier in the hallway...",
    "I'm staying low like you said. Almost to the exit.",
    "I made it outside. I can see the flames clearly now. It's getting worse.",
    "I count about 8 people outside. But I don't see Mrs. Patterson.",
    "The fire trucks are here! They're pulling up now.",
    "A firefighter is going in. Please let them know about Mrs. Patterson, 3rd floor, apartment 3C.",
    "They found her! She's coming out with a firefighter!",
  ],
  "traffic-accident": [
    "I just witnessed a bad car crash at Main Street and 3rd Avenue!",
    "Two cars collided right in the intersection. It happened maybe 30 seconds ago.",
    "One driver has a really bad cut on his head. There's a lot of blood.",
    "The other driver got out. He's walking around but he seems really confused and dizzy.",
    "The injured one is conscious. He's talking but looks dazed. Still in his car.",
    "No smoke or fuel that I can see.",
    "Wait... there's someone in the backseat of the first car!",
    "It's a small child, maybe 6 or 7 years old. They're crying but still in their car seat.",
    "I told the confused driver to sit down. He almost walked into traffic.",
    "I can hear the ambulance coming now!",
    "The paramedics are here. They're checking on the driver with the head wound first.",
  ],
}
